# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: sun
canPublishIssues: false
canPublishPullRequests: true
canPublishContributors: true
canPublishStargazers: false
canPublishCommits: false
