service: neo-data

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: us-east-1
  timeout: 900
  environment:
    DB_HOSTNAME: ${env:DB_HOSTNAME}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    ENVIRONMENT: ${env:ENVIRONMENT}
    CLOCKIFY_API_KEY: ${env:CLOCKIFY_API_KEY}
    CLOCKIFY_WORKSPACE_ID: ${env:CLOCKIFY_WORKSPACE_ID}

functions:
  update:
    handler: handler.update
    events:
      - schedule: rate(6 hours)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePipenv: false
    zip: true

package:
  exclude:
    - migrations/**
    - old_timesheet_migration/**
    - seeds/**
    - services/**
    - node_modules/**
    - setup.cfg
    - README.md
    - Pipfile
    - Pipfile.lock
    - orator_config.py
    - update_member_clt.py
    - .template.env
    - .python-version
    - .pre-commit-config.yaml
    - .codeclimate.yml

