service: neo-data

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-central1
  project: my-project
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  update_time_entries:
    handler: update_time_entries
    events:
      - http: path
  update_users:
    handler: update_users
    events:
      - http: path
  update_projects:
    handler: update_projects
    events:
      - http: path
  update_activities:
    handler: update_activities
    events:
      - http: path
  update_tags:
    handler: update_activities
    events:
      - http: path