service: clockify-integration

provider:
  name: aws
  runtime: python3.7
  timeout: 180
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - ${self:custom.clockify}
  environment:
    DB_HOSTNAME: ${env:DB_HOSTNAME}
    DB_NAME:  ${env:DB_NAME}
    DB_USERNAME:  ${env:DB_USERNAME}
    DB_PASSWORD:  ${env:DB_PASSWORD}
    DB_PORT:  ${env:DB_PORT}
    DB_URI: ${env:DB_URI}
    ENVIRONMENT:  ${env:ENVIRONMENT}
    CLOCKIFY_WORKSPACE_ID:  ${env:CLOCKIFY_WORKSPACE_ID}
    CLOCKIFY_API_KEY: ${env:CLOCKIFY_API_KEY}
    SENDGRID_API_KEY:  ${env:SENDGRID_API_KEY}
    SNS_TOPIC_NAME: ${env:SNS_TOPIC_NAME}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
  clockify:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - clockify

functions:
  daily_trigger:
    reservedConcurrency: 5
    name: daily_trigger
    handler: handler.periodic_handler
    events:
      - schedule: cron(0 6-19 * * ? *)
      - schedule: rate(1 minute)

  users:
    reservedConcurrency: 5
    name: 
    handler: handler.update_users
    events:
      - sns:
          topicName: clockify
          displayName: Clockify integration events
          filterPolicy:
            task:
              - users

  projects:
    reservedConcurrency: 5
    name: 
    handler: handler.update_projects
    events:
      - sns:
          topicName: clockify
          displayName: Clockify integration events
          filterPolicy:
            task:
              - projects

  activities:
    reservedConcurrency: 5
    name: 
    handler: handler.update_activities
    events:
      - sns:
          topicName: clockify
          displayName: Clockify integration events
          filterPolicy:
            task:
              - activities

  tags:
    reservedConcurrency: 5
    name: 
    handler: handler.update_tags
    events:
      - sns:
          topicName: clockify
          displayName: Clockify integration events
          filterPolicy:
            task:
              - tags

  time_entries:
    reservedConcurrency: 5
    name: 
    handler: handler.update_time_entries
    events:
      - sns:
          topicName: clockify
          displayName: Clockify integration events
          filterPolicy:
            task:
              - time_entries
